import type { Metadata } from 'next'
import { brand } from '@/data/brand'

const siteUrl = process.env.NEXT_PUBLIC_SITE_URL || brand.url

interface PageMetadataOptions {
  title: string
  description: string
  path: string
  ogTitle?: string
  ogDescription?: string
  /**
   * Absolute URL of the social-share image. Defaults to the root
   * opengraph-image generated by app/opengraph-image.tsx. Route
   * segments that ship their own opengraph-image.tsx (e.g. blog posts)
   * automatically override this via Next.js's file convention.
   */
  ogImage?: string
  ogImageAlt?: string
  keywords?: string[]
}

const DEFAULT_OG_IMAGE = `${siteUrl}/opengraph-image`
const DEFAULT_OG_ALT = 'Hilton Ahead — Hilton Head travel consulting, planned by a local'

export function generatePageMetadata({
  title,
  description,
  path,
  ogTitle,
  ogDescription,
  ogImage = DEFAULT_OG_IMAGE,
  ogImageAlt = DEFAULT_OG_ALT,
  keywords = [],
}: PageMetadataOptions): Metadata {
  const url = `${siteUrl}${path}`
  const images = [
    { url: ogImage, width: 1200, height: 630, alt: ogImageAlt },
  ]
  return {
    title,
    description,
    keywords,
    alternates: { canonical: url },
    openGraph: {
      title: ogTitle || title,
      description: ogDescription || description,
      url,
      siteName: brand.name,
      images,
      type: 'website',
    },
    twitter: {
      card: 'summary_large_image',
      title: ogTitle || title,
      description: ogDescription || description,
      images: [ogImage],
    },
  }
}

/**
 * Opening-hours spec used by both TravelAgency and LocalBusiness schemas.
 * Seven-day availability reflects the "text us anytime" service commitment
 * documented on /about. Adjust here if that ever changes.
 */
const OPENING_HOURS = [
  {
    '@type': 'OpeningHoursSpecification',
    dayOfWeek: [
      'Monday',
      'Tuesday',
      'Wednesday',
      'Thursday',
      'Friday',
      'Saturday',
      'Sunday',
    ],
    opens: '09:00',
    closes: '19:00',
  },
]

/**
 * JSON-LD TravelAgency schema for the homepage.
 * schema.org/TravelAgency inherits from LocalBusiness, so we include
 * address + geo so Google can attach us to the "Hilton Head, SC" map pack.
 */
export function getTravelAgencySchema() {
  const schema: Record<string, unknown> = {
    '@context': 'https://schema.org',
    '@type': 'TravelAgency',
    '@id': `${siteUrl}#travelagency`,
    name: brand.name,
    legalName: brand.legalName,
    url: siteUrl,
    logo: `${siteUrl}/logo.png`,
    image: `${siteUrl}/logo.png`,
    description: brand.shortDescription,
    priceRange: '$$',
    address: {
      '@type': 'PostalAddress',
      addressLocality: 'Hilton Head Island',
      addressRegion: 'SC',
      addressCountry: 'US',
    },
    geo: {
      '@type': 'GeoCoordinates',
      latitude: 32.2163,
      longitude: -80.7526,
    },
    openingHoursSpecification: OPENING_HOURS,
    areaServed: [
      { '@type': 'Place', name: 'Hilton Head Island' },
      { '@type': 'Place', name: 'Bluffton' },
      { '@type': 'Place', name: 'Lowcountry' },
      { '@type': 'Place', name: 'Sea Pines' },
      { '@type': 'Place', name: 'Palmetto Dunes' },
      { '@type': 'Place', name: 'Forest Beach' },
    ],
    serviceType: [
      'Custom Itineraries',
      'Villa Booking',
      'Resort Booking',
      'Group Travel Planning',
      'Wedding Travel',
      'On-Island Concierge',
      'Dining Reservations',
      'Golf Tee Times',
    ],
    knowsAbout: [
      'Hilton Head Island',
      'Sea Pines Resort',
      'Palmetto Dunes',
      'Harbour Town Golf Links',
      'Lowcountry travel',
      'South Carolina beach vacations',
    ],
  }
  if (brand.contact.email) schema.email = brand.contact.email
  if (brand.contact.phone) schema.telephone = brand.contact.phone
  return schema
}

/**
 * JSON-LD LocalBusiness — complementary to TravelAgency.
 * Google's local-pack ranking weighs LocalBusiness distinctly from
 * industry-specific subtypes like TravelAgency. Rendering both (with
 * separate @id so they link-not-duplicate in the knowledge graph) gives
 * us coverage in both map-pack surfaces and travel-vertical results.
 *
 * Accepts optional aggregate rating so we can fold real reviews in later
 * without touching page-level code.
 */
export function getLocalBusinessSchema(opts?: {
  ratingValue?: number
  reviewCount?: number
}) {
  const schema: Record<string, unknown> = {
    '@context': 'https://schema.org',
    '@type': 'LocalBusiness',
    '@id': `${siteUrl}#localbusiness`,
    name: brand.name,
    legalName: brand.legalName,
    url: siteUrl,
    logo: `${siteUrl}/logo.png`,
    image: `${siteUrl}/logo.png`,
    description: brand.shortDescription,
    priceRange: '$$',
    address: {
      '@type': 'PostalAddress',
      addressLocality: 'Hilton Head Island',
      addressRegion: 'SC',
      addressCountry: 'US',
    },
    geo: {
      '@type': 'GeoCoordinates',
      latitude: 32.2163,
      longitude: -80.7526,
    },
    openingHoursSpecification: OPENING_HOURS,
    areaServed: [
      { '@type': 'Place', name: 'Hilton Head Island, SC' },
      { '@type': 'Place', name: 'Bluffton, SC' },
      { '@type': 'Place', name: 'Daufuskie Island, SC' },
      { '@type': 'Place', name: 'Savannah, GA' },
    ],
    sameAs: [] as string[],
  }
  if (brand.contact.email) schema.email = brand.contact.email
  if (brand.contact.phone) schema.telephone = brand.contact.phone
  if (brand.social?.instagram) (schema.sameAs as string[]).push(brand.social.instagram)
  if (brand.social?.facebook) (schema.sameAs as string[]).push(brand.social.facebook)
  if ((schema.sameAs as string[]).length === 0) delete schema.sameAs
  if (opts?.ratingValue && opts?.reviewCount) {
    schema.aggregateRating = {
      '@type': 'AggregateRating',
      ratingValue: opts.ratingValue,
      reviewCount: opts.reviewCount,
      bestRating: 5,
      worstRating: 1,
    }
  }
  return schema
}

/** JSON-LD for FAQ page */
export function getFaqSchema(
  items: ReadonlyArray<{ question: string; answer: string }>,
) {
  return {
    '@context': 'https://schema.org',
    '@type': 'FAQPage',
    mainEntity: items.map((item) => ({
      '@type': 'Question',
      name: item.question,
      acceptedAnswer: { '@type': 'Answer', text: item.answer },
    })),
  }
}

/** JSON-LD BreadcrumbList */
export function getBreadcrumbSchema(items: { name: string; path: string }[]) {
  return {
    '@context': 'https://schema.org',
    '@type': 'BreadcrumbList',
    itemListElement: items.map((item, index) => ({
      '@type': 'ListItem',
      position: index + 1,
      name: item.name,
      item: `${siteUrl}${item.path}`,
    })),
  }
}

/** JSON-LD for a service page */
export function getServiceSchema(service: {
  name: string
  description: string
  path: string
}) {
  return {
    '@context': 'https://schema.org',
    '@type': 'Service',
    serviceType: service.name,
    provider: {
      '@type': 'TravelAgency',
      name: brand.name,
      url: siteUrl,
    },
    description: service.description,
    url: `${siteUrl}${service.path}`,
    areaServed: { '@type': 'Place', name: 'Hilton Head Island, SC' },
  }
}

/** JSON-LD BlogPosting for individual articles. */
export function getBlogPostingSchema(post: {
  slug: string
  title: string
  description: string
  publishedAt: string
  updatedAt?: string
  author: string
  keywords: string[]
}) {
  const url = `${siteUrl}/blog/${post.slug}`
  return {
    '@context': 'https://schema.org',
    '@type': 'BlogPosting',
    '@id': url,
    url,
    headline: post.title,
    description: post.description,
    datePublished: post.publishedAt,
    dateModified: post.updatedAt || post.publishedAt,
    author: { '@type': 'Organization', name: post.author, url: siteUrl },
    publisher: {
      '@type': 'Organization',
      name: brand.name,
      url: siteUrl,
      logo: {
        '@type': 'ImageObject',
        url: `${siteUrl}/logo.png`,
      },
    },
    mainEntityOfPage: { '@type': 'WebPage', '@id': url },
    keywords: post.keywords.join(', '),
    inLanguage: 'en-US',
    isPartOf: {
      '@type': 'Blog',
      '@id': `${siteUrl}/blog`,
      name: `${brand.name} Local Guide`,
    },
  }
}

/** JSON-LD ItemList for tier-list posts (helps rich result eligibility). */
export function getItemListSchema(
  name: string,
  items: Array<{ name: string; description?: string }>,
) {
  return {
    '@context': 'https://schema.org',
    '@type': 'ItemList',
    name,
    numberOfItems: items.length,
    itemListElement: items.map((item, index) => ({
      '@type': 'ListItem',
      position: index + 1,
      name: item.name,
      ...(item.description ? { description: item.description } : {}),
    })),
  }
}

/**
 * JSON-LD Organization — used site-wide (homepage + footer).
 * Includes aggregateRating if available. Strengthens the Knowledge Graph.
 */
export function getOrganizationSchema(opts?: {
  ratingValue?: number
  reviewCount?: number
}) {
  const base: Record<string, unknown> = {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    '@id': `${siteUrl}#organization`,
    name: brand.name,
    legalName: brand.legalName,
    url: siteUrl,
    logo: `${siteUrl}/logo.png`,
    email: brand.contact.email,
    foundingLocation: {
      '@type': 'Place',
      name: 'Hilton Head Island, SC',
    },
    address: {
      '@type': 'PostalAddress',
      addressLocality: 'Hilton Head Island',
      addressRegion: 'SC',
      addressCountry: 'US',
    },
    areaServed: [
      { '@type': 'Place', name: 'Hilton Head Island' },
      { '@type': 'Place', name: 'Bluffton, SC' },
      { '@type': 'Place', name: 'Lowcountry' },
    ],
    knowsAbout: [
      'Hilton Head Island travel',
      'Sea Pines Resort',
      'Palmetto Dunes',
      'Harbour Town Golf Links',
      'RBC Heritage',
      'Lowcountry dining',
    ],
  }
  if (opts?.ratingValue && opts?.reviewCount) {
    base.aggregateRating = {
      '@type': 'AggregateRating',
      ratingValue: opts.ratingValue,
      reviewCount: opts.reviewCount,
      bestRating: 5,
      worstRating: 1,
    }
  }
  return base
}

/**
 * JSON-LD Review — one per tier-list item. itemType is constrained to the
 * set that Google accepts in the Review rich-result spec (see
 * https://developers.google.com/search/docs/appearance/structured-data/review-snippet).
 * TouristAttraction is a valid schema.org type but is NOT on Google's list,
 * so it must not be used here or GSC will reject the rich result with
 * "Invalid object type for field itemReviewed".
 */
export function getReviewSchema(review: {
  itemName: string
  itemType: 'Restaurant' | 'LodgingBusiness' | 'LocalBusiness'
  reviewBody: string
  ratingValue: number // 1–5
  authorName: string
  datePublished: string
  locationName?: string
}) {
  return {
    '@context': 'https://schema.org',
    '@type': 'Review',
    name: `${review.itemName} review`,
    itemReviewed: {
      '@type': review.itemType,
      name: review.itemName,
      ...(review.locationName
        ? {
            address: {
              '@type': 'PostalAddress',
              addressLocality: review.locationName,
              addressRegion: 'SC',
              addressCountry: 'US',
            },
          }
        : {}),
    },
    reviewRating: {
      '@type': 'Rating',
      ratingValue: review.ratingValue,
      bestRating: 5,
      worstRating: 1,
    },
    author: { '@type': 'Organization', name: review.authorName },
    reviewBody: review.reviewBody,
    datePublished: review.datePublished,
    publisher: { '@type': 'Organization', name: brand.name, url: siteUrl },
  }
}

/** JSON-LD Place — for neighborhood landing pages. */
export function getPlaceSchema(place: {
  name: string
  description: string
  url: string
  latitude: number
  longitude: number
  containedIn?: string
}) {
  return {
    '@context': 'https://schema.org',
    '@type': 'TouristAttraction',
    name: place.name,
    description: place.description,
    url: place.url,
    geo: {
      '@type': 'GeoCoordinates',
      latitude: place.latitude,
      longitude: place.longitude,
    },
    containedInPlace: {
      '@type': 'Place',
      name: place.containedIn || 'Hilton Head Island, SC',
    },
    touristType: ['Couples', 'Families', 'Golfers', 'Groups'],
  }
}

/**
 * JSON-LD LodgingBusiness — for stays listed in the 2026 stays tier post.
 * Wrapped inside an ItemList in the caller.
 */
export function getLodgingBusinessSchema(lodging: {
  name: string
  description: string
  priceRange?: string
  ratingValue?: number
  reviewCount?: number
  locationName: string
}) {
  return {
    '@context': 'https://schema.org',
    '@type': 'LodgingBusiness',
    name: lodging.name,
    description: lodging.description,
    priceRange: lodging.priceRange || '$$$',
    address: {
      '@type': 'PostalAddress',
      addressLocality: lodging.locationName,
      addressRegion: 'SC',
      addressCountry: 'US',
    },
    ...(lodging.ratingValue && lodging.reviewCount
      ? {
          aggregateRating: {
            '@type': 'AggregateRating',
            ratingValue: lodging.ratingValue,
            reviewCount: lodging.reviewCount,
            bestRating: 5,
            worstRating: 1,
          },
        }
      : {}),
  }
}

/** JSON-LD Event — for RBC Heritage, festivals, concerts, etc. */
export function getEventSchema(event: {
  name: string
  description: string
  startDate: string // ISO
  endDate: string
  locationName: string
  url?: string
}) {
  return {
    '@context': 'https://schema.org',
    '@type': 'Event',
    name: event.name,
    description: event.description,
    startDate: event.startDate,
    endDate: event.endDate,
    eventAttendanceMode: 'https://schema.org/OfflineEventAttendanceMode',
    eventStatus: 'https://schema.org/EventScheduled',
    location: {
      '@type': 'Place',
      name: event.locationName,
      address: {
        '@type': 'PostalAddress',
        addressLocality: 'Hilton Head Island',
        addressRegion: 'SC',
        addressCountry: 'US',
      },
    },
    organizer: { '@type': 'Organization', name: brand.name, url: siteUrl },
    ...(event.url ? { url: event.url } : {}),
  }
}
