/**
 * HTML rendering for outreach emails.
 *
 * Cold-outreach norms: emails should LOOK like personal text in clients
 * that render HTML, not like marketing blasts. No logos, no buttons, no
 * bordered footers, no inline images. The HTML exists solely to:
 *
 *   1. Embed the 1x1 open-tracking pixel (plain-text bodies can't track opens).
 *   2. Wrap each outbound URL in a tracked redirector so we know which
 *      links got clicked.
 *   3. Preserve paragraph breaks the recipient sees in their plain-text view.
 *
 * Pair with sendEmailFromAdmin's multipart/alternative mode: both the
 * plain-text body (no tracking) and the HTML body (tracked) ship in the
 * same message. Clients that prefer plain text get the text; clients
 * that prefer HTML get the tracked HTML.
 */

import { trackClickUrl, trackOpenUrl } from './tracking';

const URL_RE = /(https?:\/\/[^\s<>"')\]]+)/g;

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

/**
 * Split the body into alternating text + URL segments, escape the text,
 * and wrap URLs in tracking anchors. Returns one big HTML string with
 * newlines still intact (paragraph/break logic happens next).
 */
function escapeAndLinkify(body: string, trackingId: string): string {
  const parts: string[] = [];
  let lastIdx = 0;
  let m: RegExpExecArray | null;

  // Reset before re-using a /g regex across calls.
  URL_RE.lastIndex = 0;

  while ((m = URL_RE.exec(body)) !== null) {
    if (m.index > lastIdx) {
      parts.push(escapeHtml(body.slice(lastIdx, m.index)));
    }
    const original = m[1];
    const tracked = trackClickUrl(trackingId, original);
    parts.push(
      `<a href="${escapeHtml(tracked)}" target="_blank" rel="noopener">${escapeHtml(original)}</a>`,
    );
    lastIdx = URL_RE.lastIndex;
  }
  if (lastIdx < body.length) {
    parts.push(escapeHtml(body.slice(lastIdx)));
  }
  return parts.join('');
}

/**
 * Convert escaped text with embedded `\n\n` paragraph breaks and `\n`
 * line breaks into <p>...</p> blocks. Preserves the visual shape the
 * operator wrote in the plain-text composer.
 */
function paragraphize(escapedText: string): string {
  return escapedText
    .split(/\n{2,}/)
    .map((p) => {
      const withBreaks = p.replace(/\n/g, '<br>');
      return `<p style="margin:0 0 16px;line-height:1.55;">${withBreaks}</p>`;
    })
    .join('');
}

/**
 * Render the full HTML body for a tracked outreach email.
 *
 * @param body         The plain-text email body the operator composed.
 *                     Should already include the CAN-SPAM footer (the
 *                     send action calls appendCanSpamFooter before
 *                     handing it here).
 * @param trackingId   UUID generated by newTrackingId(); the same id
 *                     is logged on the outreach_activity row so
 *                     events stitch back to the right opportunity.
 */
export function renderOutreachHtml(
  body: string,
  trackingId: string,
): string {
  const linkified = escapeAndLinkify(body, trackingId);
  const paragraphs = paragraphize(linkified);
  const pixel = trackOpenUrl(trackingId);

  // Minimal, single-column, inline-styled. Designed to render readably
  // in Gmail, Outlook, Apple Mail, and pure-text clients without
  // depending on style sheets or layout magic.
  return (
    `<!doctype html>` +
    `<html>` +
    `<head>` +
    `<meta charset="utf-8">` +
    `<meta name="viewport" content="width=device-width,initial-scale=1">` +
    `<meta name="color-scheme" content="light only">` +
    `</head>` +
    `<body style="margin:0;padding:0;background:#ffffff;` +
    `font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,` +
    `Helvetica,Arial,sans-serif;font-size:15px;color:#1a1a1a;">` +
    `<div style="max-width:600px;margin:0;padding:0;">` +
    paragraphs +
    `</div>` +
    `<img src="${escapeHtml(pixel)}" width="1" height="1" alt="" ` +
    `style="display:block;border:0;outline:none;` +
    `text-decoration:none;height:1px;width:1px;">` +
    `</body></html>`
  );
}
